spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}